CC = gcc #C compiler
CCFLAGS = - 03
LDFLAGS = - 1m

all: mmc

mmc: main.o mm. o
	$(CC) -o $@ $^ $(LDFLAGS)

mm.o: mm.c
	$(CC) -c $(CCFLAGS) $<

main.o: main.c
	$(CC) -c $(CCFLAGS) $<
clean:
	rm *.o *.mod
